#!/usr/bin/env bash
# Displays Best School 10 times but Hi on the 9th line

count=0
while [ $count = 9 ]
do
  if [ $count = 9 ]
  then
      echo "Hi"
  else
      echo "Best School"
  fi
  (( count+=1 ))
done
